[project]
name = "agrirouter"
description = "agrirouter SDK"
version = "1.0.0b1"
dynamic = ["dependencies"]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["agrirouter"]

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}
