= agrirouter-sdk-python
:imagesdir: assets/images
:toc:
:toc-title:
:toclevels: 4

[abstract]
== Abstract
image::agrirouter.svg[agrirouter]

The agrirouter is a universal data exchange platform for farmers and agricultural contractors that makes it possible to connect machinery and agricultural software, regardless of vendor or manufacturer. Agrirouter does not save data; it transfers data.
As a universal data exchange platform, agrirouter fills a gap on the way to Farming 4.0. Its underlying concept unites cross-vendor and discrimination-free data transfer. You retain full control over your data. Even data exchange with service providers (e.g. agricultural contractors) and other partners is uncomplicated: Data are very rapidly transferred via the online connection, and if you wish, is intelligently connected to other datasets.


== The current project you're looking at

This project contains the SDK for the communication with the agrirouter. Everything you need for the onboard process, secure communication and much more.

== Installation

== Running unit tests

`$ pytest`

== External resources

Here are some external resources for the development:

* https://my-agrirouter.com[My Agrirouter Website]
* https://github.com/DKE-Data/agrirouter-interface-documentation[Integration Guide]
* https://www.aef-online.org[EFDI Protobuf Definition]
